# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-04 06:29
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题不能为空', max_length=100, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章正文')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinglun', models.CharField(max_length=255, null=True, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 29, 44, 858431), verbose_name='评论的时间')),
                ('belong_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Article', verbose_name='被评论的文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Article', verbose_name='被赞文章')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-_-', max_length=20, null=True, verbose_name='留言者姓名')),
                ('email', models.CharField(blank=True, default='-_-', max_length=30, null=True, verbose_name='留言者邮箱')),
                ('massage', DjangoUeditor.models.UEditorField(blank='-_-', null=True, verbose_name='留言')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Article')),
            ],
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型名')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
                'db_table': 'TextType',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('upwd', models.CharField(max_length=255, verbose_name='密码')),
                ('uicon', models.ImageField(blank=True, default='uicon/default.jpg', null=True, upload_to='uicon/', verbose_name='头像')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unkown', '未知')], default='unkown', max_length=6, verbose_name='性别')),
                ('signature', DjangoUeditor.models.UEditorField(default='暂无个性签名', verbose_name='个性签名')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('bgimg', models.ImageField(blank=True, default='bgimg/welcome.gif', null=True, upload_to='bgimg/', verbose_name='主页背景图片')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User', verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='belong_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User', verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='article',
            name='A_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.TextType', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.User', verbose_name='发表者'),
        ),
    ]
