# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='uinfo',
            field=tinymce.models.HTMLField(default='暂无内容', verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=20, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upwd',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
    ]
