# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180531_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(default='说点什么呗……', verbose_name='正文')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型名')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
                'db_table': 'TextType',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='uinfo',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=tinymce.models.HTMLField(default='编辑个性签名', verbose_name='个性签名'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AddField(
            model_name='article',
            name='A_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.TextType', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User', verbose_name='发表者'),
        ),
    ]
