# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20180724_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pinglun',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='评论'),
        ),
    ]
