# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_article_pinglun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='A_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.TextType', verbose_name='类别'),
        ),
    ]
