# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-25 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20180724_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinglun', models.CharField(max_length=255, null=True, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 7, 25, 16, 14, 51, 90591), verbose_name='评论的时间')),
                ('belong_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Article', verbose_name='被评论的文章')),
                ('belong_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'Comment',
            },
        ),
    ]
