# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-25 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20180725_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 16, 29, 24, 302640), verbose_name='评论的时间'),
        ),
    ]
