# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-25 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20180725_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='不能为空', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 16, 31, 26, 609056), verbose_name='评论的时间'),
        ),
    ]
