# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20180725_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 17, 40, 51, 863491), verbose_name='评论的时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unkown', '未知')], default='unkown', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=tinymce.models.HTMLField(default='暂无个性签名', verbose_name='个性签名'),
        ),
    ]
