# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20180726_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 21, 23, 41, 151832), verbose_name='评论的时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upwd',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
    ]
