# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-28 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20180727_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_num',
            field=models.IntegerField(blank=True, default=0, null=True, validators=['点', '赞', '数']),
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 17, 25, 16, 843718), verbose_name='评论的时间'),
        ),
    ]
