# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-28 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20180728_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Article')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 18, 46, 4, 489283), verbose_name='评论的时间'),
        ),
    ]
