# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20180728_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User', verbose_name='点赞用户')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_num',
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 14, 28, 38, 846877), verbose_name='评论的时间'),
        ),
        migrations.AddField(
            model_name='new_likes',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Article', verbose_name='被赞文章'),
        ),
    ]
