# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 08:32
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_auto_20180730_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-add_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 16, 32, 4, 844880), verbose_name='评论的时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=DjangoUeditor.models.UEditorField(default='暂无个性签名', verbose_name='个性签名'),
        ),
    ]
