# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 09:27
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_auto_20180731_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 17, 27, 10, 832028), verbose_name='评论的时间'),
        ),
    ]
