# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-17 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_auto_20180817_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 21, 11, 8, 766036), verbose_name='评论的时间'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
